var MC = module.exports = require('emcee')
MC.model('profile', require('./models/profile.js'))
MC.model('myprofile', require('./models/myprofile.js'))
MC.model('package', require('./models/package.js'))
MC.model('keyword', require('./models/keyword.js'))
